spring:
  application:
    name: sdp-software
  messages:
    basename: locales/messages
  jpa:
    open-in-view: false
  profiles:
    active: ${PROFILES_ACTIVE:dev}
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:}
      repositories:
        enabled: false
  rabbitmq:
    addresses: ${RABBITMQ_URL}
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs
  override-with-generic-response: false

app:
  mail-box-queue: ${MAIL_BOX_QUEUE}
  notification-box-queue: ${NOTIFICATION_BOX_QUEUE}